import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Customer, PlanRequest, PipelineStatus } from '@/types/database'
import type { StoredContract } from './index'

// デモモードストア
interface DemoModeState {
  isDemoMode: boolean
  toggleDemoMode: () => void
  setDemoMode: (value: boolean) => void
}

export const useDemoModeStore = create<DemoModeState>()(
  persist(
    (set) => ({
      isDemoMode: false,
      toggleDemoMode: () => set((state) => ({ isDemoMode: !state.isDemoMode })),
      setDemoMode: (value) => set({ isDemoMode: value }),
    }),
    {
      name: 'ghouse-demo-mode',
    }
  )
)

// ヘルパー関数
const daysAgo = (days: number) => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

const monthsAgo = (months: number) => {
  const date = new Date()
  date.setMonth(date.getMonth() - months)
  return date.toISOString()
}

// デモ顧客データ（必須フィールドのみ定義、他はnull/デフォルト値）
export const DEMO_CUSTOMERS = [
  // 限定会員前顧客
  {
    id: 'demo-cust-001',
    name: '山田 太郎',
    tei_name: '山田邸',
    email: 'yamada@example.com',
    phone: '090-1234-5678',
    pipeline_status: '資料請求' as PipelineStatus,
    lead_source: 'ホームページ',
    lead_date: daysAgo(2),
    address: '東京都渋谷区神宮前1-2-3',
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-cust-002',
    name: '鈴木 花子',
    tei_name: '鈴木邸',
    email: 'suzuki@example.com',
    phone: '090-2345-6789',
    pipeline_status: 'イベント予約' as PipelineStatus,
    lead_source: 'Instagram広告',
    lead_date: daysAgo(5),
    address: '神奈川県横浜市青葉区1-1-1',
    notes: '週末の見学会に予約済み',
    created_at: daysAgo(5),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-cust-003',
    name: '佐藤 健一',
    tei_name: '佐藤邸',
    email: 'sato@example.com',
    phone: '080-3456-7890',
    pipeline_status: 'イベント参加' as PipelineStatus,
    lead_source: '完成見学会',
    lead_date: daysAgo(10),
    address: '埼玉県さいたま市浦和区2-3-4',
    notes: '先週の見学会に参加。平屋に興味あり',
    created_at: daysAgo(10),
    updated_at: daysAgo(7),
  },
  // 契約前顧客
  {
    id: 'demo-cust-004',
    name: '田中 美咲',
    tei_name: '田中邸',
    email: 'tanaka@example.com',
    phone: '090-4567-8901',
    pipeline_status: '限定会員' as PipelineStatus,
    lead_source: '紹介',
    lead_date: daysAgo(14),
    address: '千葉県船橋市本町3-4-5',
    estimated_amount: 35000000,
    notes: '予算3500万円、土地探しから希望',
    created_at: daysAgo(14),
    updated_at: daysAgo(10),
  },
  {
    id: 'demo-cust-005',
    name: '高橋 誠',
    tei_name: '高橋邸',
    email: 'takahashi@example.com',
    phone: '080-5678-9012',
    pipeline_status: '限定会員' as PipelineStatus,
    lead_source: 'YouTube',
    lead_date: daysAgo(20),
    address: '東京都世田谷区経堂4-5-6',
    estimated_amount: 42000000,
    meeting_date: daysAgo(12),
    notes: '2世帯住宅を検討中',
    created_at: daysAgo(20),
    updated_at: daysAgo(8),
  },
  {
    id: 'demo-cust-006',
    name: '伊藤 直子',
    tei_name: '伊藤邸',
    email: 'ito@example.com',
    phone: '090-6789-0123',
    pipeline_status: '面談' as PipelineStatus,
    lead_source: 'ホームページ',
    lead_date: daysAgo(30),
    meeting_date: daysAgo(5),
    address: '神奈川県川崎市中原区5-6-7',
    estimated_amount: 38000000,
    notes: '土地あり。来月中にプラン提案希望',
    created_at: daysAgo(30),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-cust-007',
    name: '渡辺 浩二',
    tei_name: '渡辺邸',
    email: 'watanabe@example.com',
    phone: '080-7890-1234',
    pipeline_status: '面談' as PipelineStatus,
    lead_source: '完成見学会',
    lead_date: daysAgo(25),
    meeting_date: daysAgo(3),
    address: '埼玉県川口市青木6-7-8',
    estimated_amount: 32000000,
    notes: 'コンパクトな平屋を希望',
    created_at: daysAgo(25),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-cust-008',
    name: '小林 優子',
    tei_name: '小林邸',
    email: 'kobayashi@example.com',
    phone: '090-8901-2345',
    pipeline_status: '建築申込' as PipelineStatus,
    lead_source: '紹介',
    lead_date: monthsAgo(2),
    meeting_date: daysAgo(40),
    application_date: daysAgo(15),
    address: '東京都杉並区荻窪7-8-9',
    estimated_amount: 45000000,
    notes: '建築申込済み。土地契約も完了',
    created_at: monthsAgo(2),
    updated_at: daysAgo(15),
  },
  {
    id: 'demo-cust-009',
    name: '加藤 大輔',
    tei_name: '加藤邸',
    email: 'kato@example.com',
    phone: '080-9012-3456',
    pipeline_status: '建築申込' as PipelineStatus,
    lead_source: 'Instagram広告',
    lead_date: monthsAgo(3),
    meeting_date: daysAgo(60),
    application_date: daysAgo(20),
    address: '千葉県柏市豊四季8-9-10',
    estimated_amount: 40000000,
    notes: 'プラン依頼中',
    created_at: monthsAgo(3),
    updated_at: daysAgo(10),
  },
  {
    id: 'demo-cust-010',
    name: '吉田 恵理',
    tei_name: '吉田邸',
    email: 'yoshida@example.com',
    phone: '090-0123-4567',
    pipeline_status: 'プラン提出' as PipelineStatus,
    lead_source: 'ホームページ',
    lead_date: monthsAgo(4),
    meeting_date: daysAgo(90),
    application_date: daysAgo(45),
    address: '神奈川県横浜市港北区9-10-11',
    estimated_amount: 48000000,
    notes: 'プラン2回目修正済み。金額調整中',
    created_at: monthsAgo(4),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-cust-011',
    name: '松本 隆',
    tei_name: '松本邸',
    email: 'matsumoto@example.com',
    phone: '080-1234-5670',
    pipeline_status: 'プラン提出' as PipelineStatus,
    lead_source: '完成見学会',
    lead_date: monthsAgo(3),
    meeting_date: daysAgo(70),
    application_date: daysAgo(35),
    address: '東京都練馬区石神井10-11-12',
    estimated_amount: 52000000,
    notes: '最終プラン確認中',
    created_at: monthsAgo(3),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-cust-012',
    name: '中村 美香',
    tei_name: '中村邸',
    email: 'nakamura@example.com',
    phone: '090-2345-6780',
    pipeline_status: '内定' as PipelineStatus,
    lead_source: '紹介',
    lead_date: monthsAgo(5),
    meeting_date: daysAgo(120),
    application_date: daysAgo(60),
    address: '埼玉県所沢市東町11-12-13',
    estimated_amount: 55000000,
    contract_amount: 54000000,
    notes: '来週契約予定',
    created_at: monthsAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-cust-013',
    name: '井上 和也',
    tei_name: '井上邸',
    email: 'inoue@example.com',
    phone: '080-3456-7891',
    pipeline_status: '内定' as PipelineStatus,
    lead_source: 'YouTube',
    lead_date: monthsAgo(4),
    meeting_date: daysAgo(100),
    application_date: daysAgo(50),
    address: '千葉県市川市八幡12-13-14',
    estimated_amount: 46000000,
    contract_amount: 45500000,
    notes: 'ローン審査中',
    created_at: monthsAgo(4),
    updated_at: daysAgo(4),
  },
  // ボツ・他決
  {
    id: 'demo-cust-014',
    name: '木村 俊介',
    tei_name: '木村邸',
    email: 'kimura@example.com',
    phone: '090-4567-8902',
    pipeline_status: 'ボツ・他決' as PipelineStatus,
    lead_source: 'ホームページ',
    lead_date: monthsAgo(3),
    meeting_date: daysAgo(80),
    address: '東京都北区赤羽13-14-15',
    estimated_amount: 35000000,
    notes: '他社で契約',
    created_at: monthsAgo(3),
    updated_at: daysAgo(30),
  },
  // 契約後顧客
  {
    id: 'demo-cust-015',
    name: '林 智子',
    tei_name: '林邸',
    email: 'hayashi@example.com',
    phone: '080-5678-9013',
    pipeline_status: '変更契約前' as PipelineStatus,
    lead_source: '紹介',
    lead_date: monthsAgo(8),
    meeting_date: monthsAgo(6),
    application_date: monthsAgo(5),
    address: '神奈川県相模原市中央区14-15-16',
    estimated_amount: 50000000,
    contract_amount: 49000000,
    notes: '変更契約に向けて打ち合わせ中',
    created_at: monthsAgo(8),
    updated_at: daysAgo(7),
  },
  {
    id: 'demo-cust-016',
    name: '清水 健太',
    tei_name: '清水邸',
    email: 'shimizu@example.com',
    phone: '090-6789-0124',
    pipeline_status: '変更契約前' as PipelineStatus,
    lead_source: '完成見学会',
    lead_date: monthsAgo(7),
    meeting_date: monthsAgo(5),
    application_date: monthsAgo(4),
    address: '埼玉県越谷市蒲生15-16-17',
    estimated_amount: 42000000,
    contract_amount: 41500000,
    notes: '着工準備中',
    created_at: monthsAgo(7),
    updated_at: daysAgo(14),
  },
  {
    id: 'demo-cust-017',
    name: '山口 さやか',
    tei_name: '山口邸',
    email: 'yamaguchi@example.com',
    phone: '080-7890-1235',
    pipeline_status: '変更契約後' as PipelineStatus,
    lead_source: 'ホームページ',
    lead_date: monthsAgo(10),
    meeting_date: monthsAgo(8),
    application_date: monthsAgo(7),
    address: '東京都足立区千住16-17-18',
    estimated_amount: 47000000,
    contract_amount: 48500000,
    notes: '建築中。上棟済み',
    created_at: monthsAgo(10),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-cust-018',
    name: '佐々木 亮',
    tei_name: '佐々木邸',
    email: 'sasaki@example.com',
    phone: '090-8901-2346',
    pipeline_status: '変更契約後' as PipelineStatus,
    lead_source: '紹介',
    lead_date: monthsAgo(12),
    meeting_date: monthsAgo(10),
    application_date: monthsAgo(9),
    address: '千葉県習志野市津田沼17-18-19',
    estimated_amount: 53000000,
    contract_amount: 54500000,
    notes: '来月引渡し予定',
    created_at: monthsAgo(12),
    updated_at: daysAgo(10),
  },
  // オーナー
  {
    id: 'demo-cust-019',
    name: '池田 雅之',
    tei_name: '池田邸',
    email: 'ikeda@example.com',
    phone: '080-9012-3457',
    pipeline_status: 'オーナー' as PipelineStatus,
    lead_source: 'ホームページ',
    lead_date: monthsAgo(18),
    meeting_date: monthsAgo(16),
    application_date: monthsAgo(15),
    address: '神奈川県藤沢市辻堂18-19-20',
    estimated_amount: 45000000,
    contract_amount: 44000000,
    notes: '2024年8月引渡し済み',
    created_at: monthsAgo(18),
    updated_at: monthsAgo(4),
  },
  {
    id: 'demo-cust-020',
    name: '前田 由紀',
    tei_name: '前田邸',
    email: 'maeda@example.com',
    phone: '090-0123-4568',
    pipeline_status: 'オーナー' as PipelineStatus,
    lead_source: '完成見学会',
    lead_date: monthsAgo(20),
    meeting_date: monthsAgo(18),
    application_date: monthsAgo(17),
    address: '東京都調布市布田19-20-21',
    estimated_amount: 51000000,
    contract_amount: 50000000,
    notes: '2024年6月引渡し済み。紹介いただけそう',
    created_at: monthsAgo(20),
    updated_at: monthsAgo(6),
  },
] as unknown as Customer[]

// デモプラン依頼データ（必須フィールドのみ定義）
export const DEMO_PLAN_REQUESTS = [
  {
    id: 'demo-pr-001',
    customer_id: 'demo-cust-009',
    customer_name: '加藤 大輔',
    tei_name: '加藤邸',
    status: '設計中',
    design_office: 'G設計室',
    designer_name: '設計太郎',
    deadline: daysAgo(-7), // 7日後
    floor_count: 2,
    total_floor_area: 120,
    notes: '2階建て、4LDK希望',
    created_at: daysAgo(20),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-pr-002',
    customer_id: 'demo-cust-010',
    customer_name: '吉田 恵理',
    tei_name: '吉田邸',
    status: '完了',
    design_office: '外部設計A',
    designer_name: '外部一郎',
    deadline: daysAgo(10),
    floor_count: 2,
    total_floor_area: 135,
    notes: 'プラン完了済み',
    created_at: daysAgo(45),
    updated_at: daysAgo(10),
  },
  {
    id: 'demo-pr-003',
    customer_id: 'demo-cust-011',
    customer_name: '松本 隆',
    tei_name: '松本邸',
    status: '確認待ち',
    design_office: 'G設計室',
    designer_name: '設計花子',
    deadline: daysAgo(-3), // 3日後
    floor_count: 2,
    total_floor_area: 140,
    notes: '吹き抜けあり',
    created_at: daysAgo(35),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-pr-004',
    customer_id: 'demo-cust-008',
    customer_name: '小林 優子',
    tei_name: '小林邸',
    status: '依頼受付',
    deadline: daysAgo(-14), // 14日後
    floor_count: 2,
    total_floor_area: 125,
    notes: '新規依頼',
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
] as unknown as PlanRequest[]

// デモ契約データ
export const DEMO_CONTRACTS: StoredContract[] = [
  {
    id: 'demo-contract-001',
    customer_id: 'demo-cust-015',
    fund_plan_id: null,
    status: '契約完了',
    contract_number: 'C-2024-0001',
    contract_date: monthsAgo(4),
    tei_name: '林邸',
    customer_name: '林 智子',
    partner_name: null,
    ownership_type: '単独',
    sales_person: 'デモ営業',
    design_person: '設計太郎',
    construction_person: null,
    ic_person: null,
    land_address: '神奈川県相模原市中央区14-15-16',
    land_area: 180,
    building_area: 110,
    product_name: 'G-house スタンダード',
    building_price: 35000000,
    option_price: 5000000,
    exterior_price: 3000000,
    other_price: 1000000,
    discount_amount: 500000,
    tax_amount: 4350000,
    total_amount: 49000000,
    payment_at_contract: 5000000,
    payment_at_start: 15000000,
    payment_at_frame: 15000000,
    payment_at_completion: 14000000,
    identity_verified: true,
    identity_doc_type: '運転免許証',
    identity_verified_date: monthsAgo(4),
    identity_verified_by: 'デモ営業',
    loan_type: '住宅ローン',
    loan_bank: 'みずほ銀行',
    loan_amount: 40000000,
    loan_approved: true,
    loan_approved_date: monthsAgo(4),
    important_notes: null,
    important_notes_date: null,
    attachments: null,
    created_by: 'demo-user',
    created_by_name: 'デモ営業',
    checked_by: 'demo-checker',
    checked_by_name: 'チェック担当',
    checked_at: monthsAgo(4),
    check_comment: '確認OK',
    approved_by: 'demo-approver',
    approved_by_name: '承認者',
    approved_at: monthsAgo(4),
    approval_comment: '承認済み',
    returned_by: null,
    returned_by_name: null,
    returned_at: null,
    return_comment: null,
    return_count: 0,
    history: [],
    notes: null,
    designated_checker_id: null,
    designated_checker_name: null,
    designated_approver_id: null,
    designated_approver_name: null,
    created_at: monthsAgo(4),
    updated_at: monthsAgo(4),
  },
  {
    id: 'demo-contract-002',
    customer_id: 'demo-cust-017',
    fund_plan_id: null,
    status: '契約完了',
    contract_number: 'C-2024-0002',
    contract_date: monthsAgo(6),
    tei_name: '山口邸',
    customer_name: '山口 さやか',
    partner_name: null,
    ownership_type: '単独',
    sales_person: 'デモ営業',
    design_person: '設計花子',
    construction_person: null,
    ic_person: null,
    land_address: '東京都足立区千住16-17-18',
    land_area: 150,
    building_area: 100,
    product_name: 'G-house プレミアム',
    building_price: 40000000,
    option_price: 3000000,
    exterior_price: 2500000,
    other_price: 500000,
    discount_amount: 0,
    tax_amount: 4600000,
    total_amount: 48500000,
    payment_at_contract: 5000000,
    payment_at_start: 15000000,
    payment_at_frame: 15000000,
    payment_at_completion: 13500000,
    identity_verified: true,
    identity_doc_type: 'マイナンバーカード',
    identity_verified_date: monthsAgo(6),
    identity_verified_by: 'デモ営業',
    loan_type: '住宅ローン',
    loan_bank: '三井住友銀行',
    loan_amount: 40000000,
    loan_approved: true,
    loan_approved_date: monthsAgo(6),
    important_notes: null,
    important_notes_date: null,
    attachments: null,
    created_by: 'demo-user',
    created_by_name: 'デモ営業',
    checked_by: 'demo-checker',
    checked_by_name: 'チェック担当',
    checked_at: monthsAgo(6),
    check_comment: null,
    approved_by: 'demo-approver',
    approved_by_name: '承認者',
    approved_at: monthsAgo(6),
    approval_comment: null,
    returned_by: null,
    returned_by_name: null,
    returned_at: null,
    return_comment: null,
    return_count: 0,
    history: [],
    notes: null,
    designated_checker_id: null,
    designated_checker_name: null,
    designated_approver_id: null,
    designated_approver_name: null,
    created_at: monthsAgo(6),
    updated_at: monthsAgo(6),
  },
  {
    id: 'demo-contract-003',
    customer_id: 'demo-cust-012',
    fund_plan_id: null,
    status: '上長承認待ち',
    contract_number: 'C-2024-0003',
    contract_date: null,
    tei_name: '中村邸',
    customer_name: '中村 美香',
    partner_name: null,
    ownership_type: '単独',
    sales_person: 'デモ営業',
    design_person: '設計太郎',
    construction_person: null,
    ic_person: null,
    land_address: '埼玉県所沢市東町11-12-13',
    land_area: 200,
    building_area: 130,
    product_name: 'G-house スタンダード',
    building_price: 42000000,
    option_price: 6000000,
    exterior_price: 3500000,
    other_price: 1000000,
    discount_amount: 1000000,
    tax_amount: 5150000,
    total_amount: 54000000,
    payment_at_contract: 5000000,
    payment_at_start: 17000000,
    payment_at_frame: 17000000,
    payment_at_completion: 15000000,
    identity_verified: true,
    identity_doc_type: '運転免許証',
    identity_verified_date: daysAgo(5),
    identity_verified_by: 'デモ営業',
    loan_type: '住宅ローン',
    loan_bank: '三菱UFJ銀行',
    loan_amount: 45000000,
    loan_approved: false,
    loan_approved_date: null,
    important_notes: null,
    important_notes_date: null,
    attachments: null,
    created_by: 'demo-user',
    created_by_name: 'デモ営業',
    checked_by: 'demo-checker',
    checked_by_name: 'チェック担当',
    checked_at: daysAgo(2),
    check_comment: '書類確認完了',
    approved_by: null,
    approved_by_name: null,
    approved_at: null,
    approval_comment: null,
    returned_by: null,
    returned_by_name: null,
    returned_at: null,
    return_comment: null,
    return_count: 0,
    history: [],
    notes: null,
    designated_checker_id: null,
    designated_checker_name: null,
    designated_approver_id: null,
    designated_approver_name: null,
    created_at: daysAgo(7),
    updated_at: daysAgo(2),
  },
]

// デモ用ユーザー
export const DEMO_USER = {
  id: 'demo-user-001',
  name: 'デモ 営業',
  email: 'demo@ghouse.co.jp',
  role: 'sales_leader' as const,
  avatar_url: null,
  department: '営業部',
  created_at: monthsAgo(24),
  updated_at: daysAgo(0),
}
