import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Customer, PlanRequest, PipelineStatus, CustomerLandStatus, LeadSource } from '@/types/database'
import type { StoredContract } from './index'

// デモモードストア
interface DemoModeState {
  isDemoMode: boolean
  toggleDemoMode: () => void
  setDemoMode: (value: boolean) => void
}

export const useDemoModeStore = create<DemoModeState>()(
  persist(
    (set) => ({
      isDemoMode: false,
      toggleDemoMode: () => set((state) => ({ isDemoMode: !state.isDemoMode })),
      setDemoMode: (value) => set({ isDemoMode: value }),
    }),
    {
      name: 'ghouse-demo-mode',
    }
  )
)

// ヘルパー関数
const daysAgo = (days: number) => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

const monthsAgo = (months: number) => {
  const date = new Date()
  date.setMonth(date.getMonth() - months)
  return date.toISOString()
}

// デモ顧客データ（リアルな営業活動を反映）
export const DEMO_CUSTOMERS = [
  // ===== 限定会員前顧客 =====
  {
    id: 'demo-cust-001',
    name: '西野 雄大',
    name_kana: 'ニシノ ユウダイ',
    partner_name: '西野 美咲',
    partner_name_kana: 'ニシノ ミサキ',
    ownership_type: '共有',
    tei_name: '西野様邸',
    email: 'y.nishino@gmail.com',
    phone: '080-4521-8834',
    pipeline_status: '資料請求' as PipelineStatus,
    lead_source: '資料請求' as LeadSource,
    lead_date: daysAgo(2),
    address: '大阪府豊中市新千里東町2-5-3',
    land_status: '土地探し中' as CustomerLandStatus,
    estimated_amount: 40000000,
    notes: '【資料請求】HP経由。LIFE+に興味あり。共働き夫婦、子供2人（5歳・3歳）。土地から探したい。予算4000万前後。',
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-cust-002',
    name: '橋本 康介',
    name_kana: 'ハシモト コウスケ',
    tei_name: '橋本様邸',
    email: 'k.hashimoto@yahoo.co.jp',
    phone: '090-7823-4456',
    pipeline_status: '資料請求' as PipelineStatus,
    lead_source: 'Instagram' as LeadSource,
    lead_date: daysAgo(4),
    address: '兵庫県西宮市甲子園口3-12-8',
    land_status: '土地探し中' as CustomerLandStatus,
    estimated_amount: 35000000,
    notes: '【Instagram経由】施工事例の写真を見て問合せ。独身30代。将来の結婚を見越して検討開始。まだ情報収集段階。',
    created_at: daysAgo(4),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-cust-003',
    name: '村上 健太',
    name_kana: 'ムラカミ ケンタ',
    partner_name: '村上 理恵',
    partner_name_kana: 'ムラカミ リエ',
    ownership_type: '共有',
    tei_name: '村上様邸',
    email: 'murakami.k@docomo.ne.jp',
    phone: '080-3345-9912',
    pipeline_status: 'イベント予約' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: daysAgo(7),
    address: '大阪府吹田市江坂町1-8-15',
    land_status: '土地探し中' as CustomerLandStatus,
    estimated_amount: 42000000,
    notes: '【MH見学予約】12/28(土)10時〜予約済み。子供3人（小3・小1・年中）。現在賃貸マンション。来年中に建てたい意向。',
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-cust-004',
    name: '岡田 大輔',
    name_kana: 'オカダ ダイスケ',
    partner_name: '岡田 由美',
    partner_name_kana: 'オカダ ユミ',
    ownership_type: '共有',
    tei_name: '岡田様邸',
    email: 'okada.d@icloud.com',
    phone: '090-1122-5567',
    pipeline_status: 'イベント参加' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: daysAgo(14),
    address: '京都府京都市左京区下鴨北野々神町15',
    land_status: '土地あり' as CustomerLandStatus,
    estimated_amount: 48000000,
    notes: '【見学会参加済】12/21見学。ご実家の土地（40坪）に建替え希望。両親と同居予定。平屋も検討中。次回アポ：1/5(日)14時〜',
    meeting_date: daysAgo(6),
    created_at: daysAgo(14),
    updated_at: daysAgo(6),
  },

  // ===== 契約前顧客（限定会員〜内定） =====
  {
    id: 'demo-cust-005',
    name: '田畑 誠一',
    name_kana: 'タバタ セイイチ',
    partner_name: '田畑 香織',
    partner_name_kana: 'タバタ カオリ',
    ownership_type: '共有',
    tei_name: '田畑様邸',
    email: 's.tabata@gmail.com',
    phone: '080-9988-3321',
    pipeline_status: '限定会員' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: daysAgo(21),
    address: '大阪府堺市北区中百舌鳥町3-5-12',
    land_status: '土地探し中' as CustomerLandStatus,
    estimated_amount: 38000000,
    notes: '【紹介】池田様（オーナー）からの紹介。夫婦+子供1人（1歳）。堺市北区〜中区で土地を探している。駅徒歩15分以内、40坪以上希望。',
    created_at: daysAgo(21),
    updated_at: daysAgo(10),
  },
  {
    id: 'demo-cust-006',
    name: '藤井 雅人',
    name_kana: 'フジイ マサト',
    tei_name: '藤井様邸',
    email: 'fujii.m@outlook.com',
    phone: '070-5544-8899',
    pipeline_status: '限定会員' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: daysAgo(18),
    address: '兵庫県尼崎市潮江1-2-3',
    land_status: '土地あり' as CustomerLandStatus,
    estimated_amount: 35000000,
    notes: '【HP問合せ】単独名義。親の土地（35坪）に建築予定。現在は実家住まい。コンパクトな2LDKで十分とのこと。',
    meeting_date: daysAgo(12),
    created_at: daysAgo(18),
    updated_at: daysAgo(8),
  },
  {
    id: 'demo-cust-007',
    name: '山本 浩二',
    name_kana: 'ヤマモト コウジ',
    partner_name: '山本 恵子',
    partner_name_kana: 'ヤマモト ケイコ',
    ownership_type: '共有',
    tei_name: '山本様邸',
    email: 'yamamoto.koji@ezweb.ne.jp',
    phone: '080-2233-7788',
    pipeline_status: '面談' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: daysAgo(30),
    meeting_date: daysAgo(5),
    address: '大阪府高槻市芥川町2-8-15',
    land_status: '土地探し中' as CustomerLandStatus,
    estimated_amount: 45000000,
    notes: '【面談済】12/22面談実施。子供2人（小5・小2）。高槻市内で土地探し中。SUUMO掲載の3件を提案済み。次回：土地現地案内1/4(土)予定。資金計画書作成中。',
    created_at: daysAgo(30),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-cust-008',
    name: '中川 真一',
    name_kana: 'ナカガワ シンイチ',
    partner_name: '中川 美穂',
    partner_name_kana: 'ナカガワ ミホ',
    ownership_type: '共有',
    tei_name: '中川様邸',
    email: 'nakagawa.s@softbank.ne.jp',
    phone: '090-6677-2211',
    pipeline_status: '面談' as PipelineStatus,
    lead_source: 'TEL問合せ' as LeadSource,
    lead_date: daysAgo(25),
    meeting_date: daysAgo(3),
    address: '奈良県奈良市学園北1-5-8',
    land_status: '土地契約済' as CustomerLandStatus,
    estimated_amount: 42000000,
    notes: '【面談済】12/24面談。土地契約済（奈良市学園前、45坪、2800万）。1月中にプラン依頼予定。LIFE+ Limitedに興味。太陽光+蓄電池希望。',
    created_at: daysAgo(25),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-cust-009',
    name: '小野 康平',
    name_kana: 'オノ コウヘイ',
    partner_name: '小野 由紀子',
    partner_name_kana: 'オノ ユキコ',
    ownership_type: '共有',
    tei_name: '小野様邸',
    email: 'ono.kohei@gmail.com',
    phone: '080-1199-4455',
    pipeline_status: '建築申込' as PipelineStatus,
    lead_source: '社員紹介' as LeadSource,
    lead_date: monthsAgo(2),
    meeting_date: daysAgo(45),
    application_date: daysAgo(14),
    address: '大阪府枚方市樟葉花園町12-5',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 52000000,
    notes: '【申込済】12/13申込金50万入金確認。土地：枚方市樟葉（52坪、3200万）12/20決済完了。プラン依頼準備中。ご主人のこだわり：書斎+ガレージ。',
    created_at: monthsAgo(2),
    updated_at: daysAgo(7),
  },
  {
    id: 'demo-cust-010',
    name: '佐々木 健',
    name_kana: 'ササキ タケシ',
    partner_name: '佐々木 麻衣',
    partner_name_kana: 'ササキ マイ',
    ownership_type: '共有',
    tei_name: '佐々木様邸',
    email: 'sasaki.t@au.com',
    phone: '090-3344-8877',
    pipeline_status: '建築申込' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: monthsAgo(3),
    meeting_date: daysAgo(60),
    application_date: daysAgo(20),
    address: '兵庫県神戸市東灘区住吉宮町3-8',
    land_status: '土地契約済' as CustomerLandStatus,
    estimated_amount: 55000000,
    notes: '【申込済】前田様（オーナー）紹介。土地契約済（東灘区、48坪、4500万）1月末決済予定。プラン設計中（G設計室・山田担当）。3階建て希望。',
    created_at: monthsAgo(3),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-cust-011',
    name: '森田 哲也',
    name_kana: 'モリタ テツヤ',
    partner_name: '森田 愛',
    partner_name_kana: 'モリタ アイ',
    ownership_type: '共有',
    tei_name: '森田様邸',
    email: 'morita.t@docomo.ne.jp',
    phone: '080-5566-1122',
    pipeline_status: 'プラン提出' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: monthsAgo(4),
    meeting_date: daysAgo(90),
    application_date: daysAgo(50),
    address: '大阪府豊中市蛍池中町2-3-15',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 48000000,
    notes: '【プラン提出済】12/20プラン2回目提出。金額調整中（予算オーバー200万）。オプション見直しで対応予定。次回：12/28金額確定打合せ。',
    created_at: monthsAgo(4),
    updated_at: daysAgo(7),
  },
  {
    id: 'demo-cust-012',
    name: '加藤 俊介',
    name_kana: 'カトウ シュンスケ',
    partner_name: '加藤 真理子',
    partner_name_kana: 'カトウ マリコ',
    ownership_type: '共有',
    tei_name: '加藤様邸',
    email: 'kato.shunsuke@icloud.com',
    phone: '070-8899-3344',
    pipeline_status: 'プラン提出' as PipelineStatus,
    lead_source: '業者紹介' as LeadSource,
    lead_date: monthsAgo(3),
    meeting_date: daysAgo(70),
    application_date: daysAgo(40),
    address: '京都府宇治市広野町西裏45-3',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 46000000,
    notes: '【プラン提出済】不動産業者（ABC不動産）紹介。最終プラン確認中。ローン事前審査：三井住友銀行4500万OK。1月上旬契約予定。',
    created_at: monthsAgo(3),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-cust-013',
    name: '井上 大樹',
    name_kana: 'イノウエ ダイキ',
    partner_name: '井上 さくら',
    partner_name_kana: 'イノウエ サクラ',
    ownership_type: '共有',
    tei_name: '井上様邸',
    email: 'inoue.daiki@gmail.com',
    phone: '080-2211-6677',
    pipeline_status: '内定' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: monthsAgo(5),
    meeting_date: daysAgo(120),
    application_date: daysAgo(70),
    decision_date: daysAgo(10),
    address: '大阪府茨木市駅前1-8-25',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 58000000,
    contract_amount: 57000000,
    notes: '【内定】12/17内定。契約予定日：1/11(土)。ローン本審査中（みずほ銀行5000万）。LIFE+ Limited + 太陽光10kW。引渡予定：2025年10月。',
    created_at: monthsAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-cust-014',
    name: '渡辺 翔太',
    name_kana: 'ワタナベ ショウタ',
    partner_name: '渡辺 彩香',
    partner_name_kana: 'ワタナベ アヤカ',
    ownership_type: '共有',
    tei_name: '渡辺様邸',
    email: 'watanabe.s@yahoo.co.jp',
    phone: '090-4455-2233',
    pipeline_status: '内定' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: monthsAgo(4),
    meeting_date: daysAgo(100),
    application_date: daysAgo(55),
    decision_date: daysAgo(5),
    address: '兵庫県芦屋市大原町8-12',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 65000000,
    contract_amount: 63000000,
    notes: '【内定】12/22内定。契約予定日：1/18(土)。ローン本審査通過済（りそな銀行5500万）。G-house Premium。引渡予定：2025年11月。',
    created_at: monthsAgo(4),
    updated_at: daysAgo(2),
  },

  // ===== ボツ・他決 =====
  {
    id: 'demo-cust-015',
    name: '松田 健一',
    name_kana: 'マツダ ケンイチ',
    tei_name: '松田様邸',
    email: 'matsuda.k@gmail.com',
    phone: '080-7788-1199',
    pipeline_status: 'ボツ・他決' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: monthsAgo(3),
    meeting_date: daysAgo(75),
    address: '大阪府吹田市山田西2-5-8',
    land_status: '土地探し中' as CustomerLandStatus,
    estimated_amount: 38000000,
    notes: '【他決】12/15他社（○○ハウス）で契約。価格差500万。次回の参考に。',
    created_at: monthsAgo(3),
    updated_at: daysAgo(12),
  },
  {
    id: 'demo-cust-016',
    name: '高田 裕子',
    name_kana: 'タカダ ユウコ',
    tei_name: '高田様邸',
    email: 'takada.y@softbank.ne.jp',
    phone: '090-3322-5544',
    pipeline_status: 'ボツ・他決' as PipelineStatus,
    lead_source: '資料請求' as LeadSource,
    lead_date: monthsAgo(2),
    address: '京都府京都市伏見区深草1-2-3',
    land_status: '土地探し中' as CustomerLandStatus,
    estimated_amount: 32000000,
    notes: '【ボツ】予算合わず。マンション購入に方針転換とのこと。',
    created_at: monthsAgo(2),
    updated_at: daysAgo(25),
  },

  // ===== 契約後顧客 =====
  {
    id: 'demo-cust-017',
    name: '石井 正人',
    name_kana: 'イシイ マサト',
    partner_name: '石井 美紀',
    partner_name_kana: 'イシイ ミキ',
    ownership_type: '共有',
    tei_name: '石井様邸',
    email: 'ishii.m@docomo.ne.jp',
    phone: '080-1234-5678',
    pipeline_status: '変更契約前' as PipelineStatus,
    lead_source: '社員紹介' as LeadSource,
    lead_date: monthsAgo(8),
    meeting_date: monthsAgo(6),
    application_date: monthsAgo(5),
    address: '大阪府箕面市船場東2-5-8',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 54000000,
    contract_amount: 53000000,
    notes: '【契約済】11/15契約。変更契約打合せ中。追加：ウッドデッキ+カーポート。変更契約予定：1/15。着工予定：2月上旬。',
    created_at: monthsAgo(8),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-cust-018',
    name: '木下 達也',
    name_kana: 'キノシタ タツヤ',
    partner_name: '木下 千尋',
    partner_name_kana: 'キノシタ チヒロ',
    ownership_type: '共有',
    tei_name: '木下様邸',
    email: 'kinoshita.t@au.com',
    phone: '090-5678-1234',
    pipeline_status: '変更契約前' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: monthsAgo(7),
    meeting_date: monthsAgo(5),
    application_date: monthsAgo(4),
    address: '兵庫県伊丹市荒牧3-8-15',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 47000000,
    contract_amount: 46500000,
    notes: '【契約済】10/20契約。着工準備中。確認申請提出済み。着工予定：1月中旬。完成予定：7月。',
    created_at: monthsAgo(7),
    updated_at: daysAgo(7),
  },
  {
    id: 'demo-cust-019',
    name: '長谷川 亮',
    name_kana: 'ハセガワ リョウ',
    partner_name: '長谷川 奈々',
    partner_name_kana: 'ハセガワ ナナ',
    ownership_type: '共有',
    tei_name: '長谷川様邸',
    email: 'hasegawa.r@gmail.com',
    phone: '080-8765-4321',
    pipeline_status: '変更契約後' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: monthsAgo(10),
    meeting_date: monthsAgo(8),
    application_date: monthsAgo(7),
    address: '大阪府高槻市城北町1-5-12',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 51000000,
    contract_amount: 52500000,
    notes: '【建築中】9/1着工。現在上棟済み（12/10）。順調に進行中。完成予定：3月下旬。IC打合せ2回完了。',
    created_at: monthsAgo(10),
    updated_at: daysAgo(17),
  },
  {
    id: 'demo-cust-020',
    name: '吉村 大介',
    name_kana: 'ヨシムラ ダイスケ',
    partner_name: '吉村 恵',
    partner_name_kana: 'ヨシムラ メグミ',
    ownership_type: '共有',
    tei_name: '吉村様邸',
    email: 'yoshimura.d@icloud.com',
    phone: '070-4321-8765',
    pipeline_status: '変更契約後' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: monthsAgo(12),
    meeting_date: monthsAgo(10),
    application_date: monthsAgo(9),
    address: '奈良県生駒市谷田町850-5',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 56000000,
    contract_amount: 57500000,
    notes: '【建築中】7/15着工。外壁工事中。完成予定：2月中旬。引渡予定：2月末。来週施主検査予定。',
    created_at: monthsAgo(12),
    updated_at: daysAgo(5),
  },

  // ===== オーナー =====
  {
    id: 'demo-cust-021',
    name: '池田 雅彦',
    name_kana: 'イケダ マサヒコ',
    partner_name: '池田 真由美',
    partner_name_kana: 'イケダ マユミ',
    ownership_type: '共有',
    tei_name: '池田様邸',
    email: 'ikeda.m@ezweb.ne.jp',
    phone: '080-9012-3456',
    pipeline_status: 'オーナー' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: monthsAgo(18),
    meeting_date: monthsAgo(16),
    application_date: monthsAgo(15),
    address: '大阪府堺市北区中百舌鳥町5-8-12',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 49000000,
    contract_amount: 48000000,
    notes: '【オーナー】2024年7月引渡。LIFE+ Standard。太陽光8kW。とても満足いただいており、紹介1件（田畑様）いただいた。定期点検：6ヶ月点検完了。',
    created_at: monthsAgo(18),
    updated_at: monthsAgo(5),
  },
  {
    id: 'demo-cust-022',
    name: '前田 哲夫',
    name_kana: 'マエダ テツオ',
    partner_name: '前田 由紀',
    partner_name_kana: 'マエダ ユキ',
    ownership_type: '共有',
    tei_name: '前田様邸',
    email: 'maeda.t@gmail.com',
    phone: '090-0123-4568',
    pipeline_status: 'オーナー' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: monthsAgo(22),
    meeting_date: monthsAgo(20),
    application_date: monthsAgo(19),
    address: '兵庫県西宮市甲東園1-3-8',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 55000000,
    contract_amount: 54000000,
    notes: '【オーナー】2024年5月引渡。G-house Premium。紹介1件（佐々木様）いただいた。1年点検予定：2025年5月。',
    created_at: monthsAgo(22),
    updated_at: monthsAgo(7),
  },
  {
    id: 'demo-cust-023',
    name: '川口 修一',
    name_kana: 'カワグチ シュウイチ',
    partner_name: '川口 美咲',
    partner_name_kana: 'カワグチ ミサキ',
    ownership_type: '共有',
    tei_name: '川口様邸',
    email: 'kawaguchi.s@yahoo.co.jp',
    phone: '080-6789-0123',
    pipeline_status: 'オーナー' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: monthsAgo(26),
    meeting_date: monthsAgo(24),
    application_date: monthsAgo(23),
    address: '京都府長岡京市天神2-5-18',
    land_status: '土地決済済' as CustomerLandStatus,
    estimated_amount: 52000000,
    contract_amount: 51000000,
    notes: '【オーナー】2024年2月引渡。LIFE+ Limited。1年点検完了。外構追加工事（カーポート）実施済み。',
    created_at: monthsAgo(26),
    updated_at: monthsAgo(10),
  },
] as unknown as Customer[]

// デモプラン依頼データ
export const DEMO_PLAN_REQUESTS = [
  {
    id: 'demo-pr-001',
    customer_id: 'demo-cust-009',
    customer_name: '小野 康平',
    tei_name: '小野様邸',
    status: '設計中',
    design_office: 'G設計室',
    designer_name: '山田 一郎',
    deadline: daysAgo(-7),
    floor_count: 2,
    total_floor_area: 125,
    notes: '2階建て、4LDK+書斎+ガレージ。LIFE+ Limited。太陽光10kW希望。',
    created_at: daysAgo(14),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-pr-002',
    customer_id: 'demo-cust-010',
    customer_name: '佐々木 健',
    tei_name: '佐々木様邸',
    status: '設計中',
    design_office: 'G設計室',
    designer_name: '鈴木 花子',
    deadline: daysAgo(-3),
    floor_count: 3,
    total_floor_area: 140,
    notes: '3階建て、5LDK。東灘区。狭小地のため3階建て。ルーフバルコニー希望。',
    created_at: daysAgo(20),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-pr-003',
    customer_id: 'demo-cust-011',
    customer_name: '森田 哲也',
    tei_name: '森田様邸',
    status: '確認待ち',
    design_office: '外部設計A',
    designer_name: '田中 健二',
    deadline: daysAgo(3),
    floor_count: 2,
    total_floor_area: 118,
    notes: 'プラン2回目。金額調整済み。お客様確認待ち。',
    created_at: daysAgo(50),
    updated_at: daysAgo(7),
  },
  {
    id: 'demo-pr-004',
    customer_id: 'demo-cust-012',
    customer_name: '加藤 俊介',
    tei_name: '加藤様邸',
    status: '完了',
    design_office: 'G設計室',
    designer_name: '山田 一郎',
    deadline: daysAgo(10),
    floor_count: 2,
    total_floor_area: 122,
    notes: '最終プラン確定。契約準備中。',
    created_at: daysAgo(40),
    updated_at: daysAgo(2),
  },
] as unknown as PlanRequest[]

// デモ契約データ
export const DEMO_CONTRACTS: StoredContract[] = [
  {
    id: 'demo-contract-001',
    customer_id: 'demo-cust-017',
    fund_plan_id: null,
    status: '契約完了',
    contract_number: 'C-2024-0015',
    contract_date: monthsAgo(1),
    tei_name: '石井様邸',
    customer_name: '石井 正人',
    partner_name: '石井 美紀',
    ownership_type: '共有',
    sales_person: '田畑 美香',
    design_person: '山田 一郎',
    construction_person: '工事 太郎',
    ic_person: null,
    land_address: '大阪府箕面市船場東2-5-8',
    land_area: 165,
    building_area: 115,
    product_name: 'LIFE+ Limited',
    building_price: 38000000,
    option_price: 6500000,
    exterior_price: 4000000,
    other_price: 1500000,
    discount_amount: 500000,
    tax_amount: 4950000,
    total_amount: 53000000,
    payment_at_contract: 5000000,
    payment_at_start: 16000000,
    payment_at_frame: 16000000,
    payment_at_completion: 16000000,
    identity_verified: true,
    identity_doc_type: '運転免許証',
    identity_verified_date: monthsAgo(1),
    identity_verified_by: '田畑 美香',
    loan_type: '住宅ローン',
    loan_bank: '三井住友銀行',
    loan_amount: 45000000,
    loan_approved: true,
    loan_approved_date: monthsAgo(1),
    important_notes: null,
    important_notes_date: null,
    attachments: null,
    created_by: 'demo-user',
    created_by_name: '田畑 美香',
    checked_by: 'demo-checker',
    checked_by_name: '営業リーダー',
    checked_at: monthsAgo(1),
    check_comment: '確認OK',
    approved_by: 'demo-approver',
    approved_by_name: '部長',
    approved_at: monthsAgo(1),
    approval_comment: null,
    returned_by: null,
    returned_by_name: null,
    returned_at: null,
    return_comment: null,
    return_count: 0,
    history: [],
    notes: '変更契約準備中',
    designated_checker_id: null,
    designated_checker_name: null,
    designated_approver_id: null,
    designated_approver_name: null,
    created_at: monthsAgo(1),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-contract-002',
    customer_id: 'demo-cust-019',
    fund_plan_id: null,
    status: '契約完了',
    contract_number: 'C-2024-0012',
    contract_date: monthsAgo(4),
    tei_name: '長谷川様邸',
    customer_name: '長谷川 亮',
    partner_name: '長谷川 奈々',
    ownership_type: '共有',
    sales_person: '田畑 美香',
    design_person: '鈴木 花子',
    construction_person: '工事 二郎',
    ic_person: 'IC 美咲',
    land_address: '大阪府高槻市城北町1-5-12',
    land_area: 172,
    building_area: 125,
    product_name: 'LIFE+ Standard',
    building_price: 36000000,
    option_price: 8000000,
    exterior_price: 4500000,
    other_price: 2000000,
    discount_amount: 1000000,
    tax_amount: 4950000,
    total_amount: 52500000,
    payment_at_contract: 5000000,
    payment_at_start: 16000000,
    payment_at_frame: 16000000,
    payment_at_completion: 15500000,
    identity_verified: true,
    identity_doc_type: 'マイナンバーカード',
    identity_verified_date: monthsAgo(4),
    identity_verified_by: '田畑 美香',
    loan_type: '住宅ローン',
    loan_bank: 'みずほ銀行',
    loan_amount: 45000000,
    loan_approved: true,
    loan_approved_date: monthsAgo(4),
    important_notes: null,
    important_notes_date: null,
    attachments: null,
    created_by: 'demo-user',
    created_by_name: '田畑 美香',
    checked_by: 'demo-checker',
    checked_by_name: '営業リーダー',
    checked_at: monthsAgo(4),
    check_comment: null,
    approved_by: 'demo-approver',
    approved_by_name: '部長',
    approved_at: monthsAgo(4),
    approval_comment: null,
    returned_by: null,
    returned_by_name: null,
    returned_at: null,
    return_comment: null,
    return_count: 0,
    history: [],
    notes: '上棟完了。順調に進行中。',
    designated_checker_id: null,
    designated_checker_name: null,
    designated_approver_id: null,
    designated_approver_name: null,
    created_at: monthsAgo(4),
    updated_at: daysAgo(17),
  },
  {
    id: 'demo-contract-003',
    customer_id: 'demo-cust-013',
    fund_plan_id: null,
    status: '上長承認待ち',
    contract_number: 'C-2025-0001',
    contract_date: null,
    tei_name: '井上様邸',
    customer_name: '井上 大樹',
    partner_name: '井上 さくら',
    ownership_type: '共有',
    sales_person: '田畑 美香',
    design_person: '山田 一郎',
    construction_person: null,
    ic_person: null,
    land_address: '大阪府茨木市駅前1-8-25',
    land_area: 185,
    building_area: 132,
    product_name: 'LIFE+ Limited',
    building_price: 42000000,
    option_price: 7500000,
    exterior_price: 4500000,
    other_price: 2000000,
    discount_amount: 1000000,
    tax_amount: 5500000,
    total_amount: 57000000,
    payment_at_contract: 5000000,
    payment_at_start: 17000000,
    payment_at_frame: 18000000,
    payment_at_completion: 17000000,
    identity_verified: true,
    identity_doc_type: '運転免許証',
    identity_verified_date: daysAgo(10),
    identity_verified_by: '田畑 美香',
    loan_type: '住宅ローン',
    loan_bank: 'みずほ銀行',
    loan_amount: 50000000,
    loan_approved: false,
    loan_approved_date: null,
    important_notes: null,
    important_notes_date: null,
    attachments: null,
    created_by: 'demo-user',
    created_by_name: '田畑 美香',
    checked_by: 'demo-checker',
    checked_by_name: '営業リーダー',
    checked_at: daysAgo(5),
    check_comment: '書類確認OK',
    approved_by: null,
    approved_by_name: null,
    approved_at: null,
    approval_comment: null,
    returned_by: null,
    returned_by_name: null,
    returned_at: null,
    return_comment: null,
    return_count: 0,
    history: [],
    notes: '1/11契約予定。ローン本審査中。',
    designated_checker_id: null,
    designated_checker_name: null,
    designated_approver_id: null,
    designated_approver_name: null,
    created_at: daysAgo(12),
    updated_at: daysAgo(1),
  },
]

// デモ用ユーザー
export const DEMO_USER = {
  id: 'demo-user-001',
  name: '田畑 美香',
  email: 'tabata@ghouse.co.jp',
  role: 'sales_leader' as const,
  avatar_url: null,
  department: '営業部',
  created_at: monthsAgo(24),
  updated_at: daysAgo(0),
}
