import type { Customer, PipelineStatus, LeadSource } from '@/types/database'

// サンプル顧客データ
export const sampleCustomers: Omit<Customer, 'id' | 'created_at' | 'updated_at'>[] = [
  // 反響段階
  {
    tenant_id: null,
    name: '高橋 健太',
    name_kana: 'タカハシ ケンタ',
    email: 'takahashi.kenta@example.com',
    phone: '090-1234-5678',
    phone2: null,
    postal_code: '530-0001',
    address: '大阪府大阪市北区梅田1-1-1',
    tei_name: '高橋様邸',
    partner_name: '高橋 美咲',
    partner_name_kana: 'タカハシ ミサキ',
    ownership_type: '共有',
    pipeline_status: '反響' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: '2024-12-11',
    event_date: null,
    member_date: null,
    meeting_date: null,
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 35000000,
    contract_amount: null,
    notes: 'Webからの問い合わせ。戸建てに興味あり。夫婦+子供2人の家族構成。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '中村 真由美',
    name_kana: 'ナカムラ マユミ',
    email: 'nakamura.mayumi@example.com',
    phone: '090-2345-6789',
    phone2: null,
    postal_code: '532-0011',
    address: '大阪府大阪市淀川区西中島5-2-3',
    tei_name: '中村様邸',
    partner_name: null,
    partner_name_kana: null,
    ownership_type: '単独',
    pipeline_status: '反響' as PipelineStatus,
    lead_source: 'Instagram' as LeadSource,
    lead_date: '2024-12-12',
    event_date: null,
    member_date: null,
    meeting_date: null,
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 27000000,
    contract_amount: null,
    notes: 'Instagram広告からの問い合わせ。平屋希望。単身。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '小林 大輔',
    name_kana: 'コバヤシ ダイスケ',
    email: 'kobayashi.daisuke@example.com',
    phone: '080-3456-7890',
    phone2: null,
    postal_code: '536-0007',
    address: '大阪府大阪市城東区成育3-4-5',
    tei_name: '小林様邸',
    partner_name: '小林 恵子',
    partner_name_kana: 'コバヤシ ケイコ',
    ownership_type: '共有',
    pipeline_status: '反響' as PipelineStatus,
    lead_source: 'その他' as LeadSource,
    lead_date: '2024-12-13',
    event_date: null,
    member_date: null,
    meeting_date: null,
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 40000000,
    contract_amount: null,
    notes: 'チラシを見て問い合わせ。2階建て希望。夫婦。',
    kintone_record_id: null,
  },

  // イベント参加段階
  {
    tenant_id: null,
    name: '渡辺 裕子',
    name_kana: 'ワタナベ ユウコ',
    email: 'watanabe.yuko@example.com',
    phone: '090-4567-8901',
    phone2: null,
    postal_code: '565-0853',
    address: '大阪府吹田市春日4-5-6',
    tei_name: '渡辺様邸',
    partner_name: '渡辺 浩',
    partner_name_kana: 'ワタナベ ヒロシ',
    ownership_type: '共有',
    pipeline_status: 'イベント参加' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: '2024-12-08',
    event_date: '2024-12-10',
    member_date: null,
    meeting_date: null,
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 32000000,
    contract_amount: null,
    notes: '完成見学会に参加。ZEH住宅に興味。夫婦+子供1人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '伊藤 隆',
    name_kana: 'イトウ タカシ',
    email: 'ito.takashi@example.com',
    phone: '080-5678-9012',
    phone2: null,
    postal_code: '561-0881',
    address: '大阪府豊中市中桜塚2-3-4',
    tei_name: '伊藤様邸',
    partner_name: '伊藤 麻衣',
    partner_name_kana: 'イトウ マイ',
    ownership_type: '共有',
    pipeline_status: 'イベント参加' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: '2024-12-05',
    event_date: '2024-12-08',
    member_date: null,
    meeting_date: null,
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 48000000,
    contract_amount: null,
    notes: 'モデルハウス見学済み。広めのLDK希望。夫婦+子供3人。',
    kintone_record_id: null,
  },

  // 限定会員段階
  {
    tenant_id: null,
    name: '山本 さくら',
    name_kana: 'ヤマモト サクラ',
    email: 'yamamoto.sakura@example.com',
    phone: '090-6789-0123',
    phone2: null,
    postal_code: '560-0021',
    address: '大阪府豊中市本町3-4-5',
    tei_name: '山本様邸',
    partner_name: '山本 翔太',
    partner_name_kana: 'ヤマモト ショウタ',
    ownership_type: '共有',
    pipeline_status: '限定会員' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: '2024-11-25',
    event_date: '2024-11-28',
    member_date: '2024-12-01',
    meeting_date: null,
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 38000000,
    contract_amount: null,
    notes: '既存顧客からの紹介。太陽光+蓄電池希望。夫婦+子供2人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '加藤 誠一',
    name_kana: 'カトウ セイイチ',
    email: 'kato.seiichi@example.com',
    phone: '080-7890-1234',
    phone2: null,
    postal_code: '573-0032',
    address: '大阪府枚方市岡東町5-6-7',
    tei_name: '加藤様邸',
    partner_name: '加藤 智子',
    partner_name_kana: 'カトウ トモコ',
    ownership_type: '共有',
    pipeline_status: '限定会員' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: '2024-11-20',
    event_date: '2024-11-22',
    member_date: '2024-11-28',
    meeting_date: null,
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 43000000,
    contract_amount: null,
    notes: '限定会員登録済み。長期優良住宅希望。夫婦。',
    kintone_record_id: null,
  },

  // 面談段階
  {
    tenant_id: null,
    name: '山田 太郎',
    name_kana: 'ヤマダ タロウ',
    email: 'yamada.taro@example.com',
    phone: '090-8901-2345',
    phone2: null,
    postal_code: '535-0002',
    address: '大阪府大阪市旭区大宮1-2-3',
    tei_name: '山田様邸',
    partner_name: '山田 花子',
    partner_name_kana: 'ヤマダ ハナコ',
    ownership_type: '共有',
    pipeline_status: '面談' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: '2024-11-15',
    event_date: '2024-11-18',
    member_date: '2024-11-22',
    meeting_date: '2024-11-28',
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 45,
    building_area: 32,
    product_id: null,
    estimated_amount: 35000000,
    contract_amount: null,
    notes: '初回面談実施済み。土地探しから。夫婦+子供2人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '松本 恵子',
    name_kana: 'マツモト ケイコ',
    email: 'matsumoto.keiko@example.com',
    phone: '080-9012-3456',
    phone2: null,
    postal_code: '570-0043',
    address: '大阪府守口市南寺方東通2-3-4',
    tei_name: '松本様邸',
    partner_name: '松本 健二',
    partner_name_kana: 'マツモト ケンジ',
    ownership_type: '共有',
    pipeline_status: '面談' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: '2024-11-10',
    event_date: '2024-11-14',
    member_date: '2024-11-18',
    meeting_date: '2024-11-25',
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 60,
    building_area: 50,
    product_id: null,
    estimated_amount: 55000000,
    contract_amount: null,
    notes: '二世帯住宅を検討中。プラン提案済み。夫婦+子供1人+両親。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '井上 浩二',
    name_kana: 'イノウエ コウジ',
    email: 'inoue.koji@example.com',
    phone: '090-0123-4567',
    phone2: null,
    postal_code: '578-0941',
    address: '大阪府東大阪市岩田町3-4-5',
    tei_name: '井上様邸',
    partner_name: '井上 美穂',
    partner_name_kana: 'イノウエ ミホ',
    ownership_type: '共有',
    pipeline_status: '面談' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: '2024-11-08',
    event_date: '2024-11-10',
    member_date: '2024-11-15',
    meeting_date: '2024-11-22',
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 50,
    building_area: 28,
    product_id: null,
    estimated_amount: 32000000,
    contract_amount: null,
    notes: '平屋希望。土地は決定済み。夫婦。',
    kintone_record_id: null,
  },

  // 建築申込段階
  {
    tenant_id: null,
    name: '佐藤 花子',
    name_kana: 'サトウ ハナコ',
    email: 'sato.hanako@example.com',
    phone: '080-1234-5678',
    phone2: null,
    postal_code: '531-0041',
    address: '大阪府大阪市北区天神橋4-5-6',
    tei_name: '佐藤様邸',
    partner_name: '佐藤 健太',
    partner_name_kana: 'サトウ ケンタ',
    ownership_type: '共有',
    pipeline_status: '建築申込' as PipelineStatus,
    lead_source: 'Instagram' as LeadSource,
    lead_date: '2024-10-20',
    event_date: '2024-10-25',
    member_date: '2024-10-30',
    meeting_date: '2024-11-05',
    application_date: '2024-11-15',
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 48,
    building_area: 35,
    product_id: null,
    estimated_amount: 40000000,
    contract_amount: null,
    notes: '建築申込済み。資金計画確定。夫婦+子供2人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '森田 優',
    name_kana: 'モリタ ユウ',
    email: 'morita.yu@example.com',
    phone: '090-2345-6780',
    phone2: null,
    postal_code: '564-0043',
    address: '大阪府吹田市南吹田4-5-6',
    tei_name: '森田様邸',
    partner_name: '森田 由美',
    partner_name_kana: 'モリタ ユミ',
    ownership_type: '共有',
    pipeline_status: '建築申込' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: '2024-10-15',
    event_date: '2024-10-20',
    member_date: '2024-10-25',
    meeting_date: '2024-11-01',
    application_date: '2024-11-10',
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 52,
    building_area: 38,
    product_id: null,
    estimated_amount: 38000000,
    contract_amount: null,
    notes: 'プラン確定済み。仕様打ち合わせ中。夫婦+子供1人。',
    kintone_record_id: null,
  },

  // 内定段階
  {
    tenant_id: null,
    name: '田中 美咲',
    name_kana: 'タナカ ミサキ',
    email: 'tanaka.misaki@example.com',
    phone: '090-3456-7891',
    phone2: null,
    postal_code: '567-0032',
    address: '大阪府茨木市西駅前町5-6-7',
    tei_name: '田中様邸',
    partner_name: '田中 誠',
    partner_name_kana: 'タナカ マコト',
    ownership_type: '共有',
    pipeline_status: '内定' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: '2024-09-20',
    event_date: '2024-09-25',
    member_date: '2024-10-01',
    meeting_date: '2024-10-08',
    application_date: '2024-10-20',
    decision_date: '2024-11-01',
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 55,
    building_area: 42,
    product_id: null,
    estimated_amount: 50000000,
    contract_amount: null,
    notes: '内定済み。契約準備中。夫婦+子供3人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '吉田 健一',
    name_kana: 'ヨシダ ケンイチ',
    email: 'yoshida.kenichi@example.com',
    phone: '080-4567-8902',
    phone2: null,
    postal_code: '569-0803',
    address: '大阪府高槻市高槻町6-7-8',
    tei_name: '吉田様邸',
    partner_name: '吉田 理香',
    partner_name_kana: 'ヨシダ リカ',
    ownership_type: '共有',
    pipeline_status: '内定' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: '2024-09-10',
    event_date: '2024-09-15',
    member_date: '2024-09-20',
    meeting_date: '2024-09-28',
    application_date: '2024-10-10',
    decision_date: '2024-10-25',
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 50,
    building_area: 36,
    product_id: null,
    estimated_amount: 42000000,
    contract_amount: null,
    notes: '内定。ローン事前審査通過。夫婦。',
    kintone_record_id: null,
  },

  // 契約段階
  {
    tenant_id: null,
    name: '鈴木 一郎',
    name_kana: 'スズキ イチロウ',
    email: 'suzuki.ichiro@example.com',
    phone: '090-5678-9013',
    phone2: null,
    postal_code: '540-0012',
    address: '大阪府大阪市中央区谷町3-4-5',
    tei_name: '鈴木様邸',
    partner_name: '鈴木 美穂',
    partner_name_kana: 'スズキ ミホ',
    ownership_type: '共有',
    pipeline_status: '契約' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: '2024-08-15',
    event_date: '2024-08-20',
    member_date: '2024-08-25',
    meeting_date: '2024-09-01',
    application_date: '2024-09-15',
    decision_date: '2024-09-30',
    contract_date: '2024-10-15',
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 52,
    building_area: 40,
    product_id: null,
    estimated_amount: 45000000,
    contract_amount: 44000000,
    notes: '契約締結済み。変更契約準備中。夫婦+子供2人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '石井 理恵',
    name_kana: 'イシイ リエ',
    email: 'ishii.rie@example.com',
    phone: '080-6789-0124',
    phone2: null,
    postal_code: '543-0021',
    address: '大阪府大阪市天王寺区東高津町4-5-6',
    tei_name: '石井様邸',
    partner_name: '石井 翔',
    partner_name_kana: 'イシイ ショウ',
    ownership_type: '共有',
    pipeline_status: '契約' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: '2024-08-01',
    event_date: '2024-08-05',
    member_date: '2024-08-10',
    meeting_date: '2024-08-18',
    application_date: '2024-09-01',
    decision_date: '2024-09-15',
    contract_date: '2024-10-01',
    groundbreaking_date: null,
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 48,
    building_area: 35,
    product_id: null,
    estimated_amount: 38000000,
    contract_amount: 37500000,
    notes: '契約済み。仕様変更検討中。夫婦+子供1人。',
    kintone_record_id: null,
  },

  // 着工段階
  {
    tenant_id: null,
    name: '木村 拓也',
    name_kana: 'キムラ タクヤ',
    email: 'kimura.takuya@example.com',
    phone: '090-7890-1235',
    phone2: null,
    postal_code: '545-0011',
    address: '大阪府大阪市阿倍野区昭和町2-3-4',
    tei_name: '木村様邸',
    partner_name: '木村 恵',
    partner_name_kana: 'キムラ メグミ',
    ownership_type: '共有',
    pipeline_status: '着工' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: '2024-06-01',
    event_date: '2024-06-05',
    member_date: '2024-06-10',
    meeting_date: '2024-06-18',
    application_date: '2024-07-01',
    decision_date: '2024-07-15',
    contract_date: '2024-08-01',
    groundbreaking_date: '2024-10-01',
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 55,
    building_area: 42,
    product_id: null,
    estimated_amount: 48000000,
    contract_amount: 47000000,
    notes: '着工済み。基礎工事中。夫婦+子供2人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '斎藤 真理子',
    name_kana: 'サイトウ マリコ',
    email: 'saito.mariko@example.com',
    phone: '080-8901-2346',
    phone2: null,
    postal_code: '558-0022',
    address: '大阪府大阪市住吉区杉本3-4-5',
    tei_name: '斎藤様邸',
    partner_name: '斎藤 大介',
    partner_name_kana: 'サイトウ ダイスケ',
    ownership_type: '共有',
    pipeline_status: '着工' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: '2024-05-15',
    event_date: '2024-05-20',
    member_date: '2024-05-25',
    meeting_date: '2024-06-01',
    application_date: '2024-06-15',
    decision_date: '2024-07-01',
    contract_date: '2024-07-15',
    groundbreaking_date: '2024-09-15',
    handover_date: null,
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 65,
    building_area: 55,
    product_id: null,
    estimated_amount: 58000000,
    contract_amount: 56000000,
    notes: '二世帯住宅着工中。上棟予定1月。夫婦+両親。',
    kintone_record_id: null,
  },

  // 引渡段階
  {
    tenant_id: null,
    name: '清水 正義',
    name_kana: 'シミズ マサヨシ',
    email: 'shimizu.masayoshi@example.com',
    phone: '090-9012-3457',
    phone2: null,
    postal_code: '559-0024',
    address: '大阪府大阪市住之江区新北島5-6-7',
    tei_name: '清水様邸',
    partner_name: '清水 さやか',
    partner_name_kana: 'シミズ サヤカ',
    ownership_type: '共有',
    pipeline_status: '引渡' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: '2024-03-01',
    event_date: '2024-03-05',
    member_date: '2024-03-10',
    meeting_date: '2024-03-18',
    application_date: '2024-04-01',
    decision_date: '2024-04-15',
    contract_date: '2024-05-01',
    groundbreaking_date: '2024-07-01',
    handover_date: '2025-01-10',
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 48,
    building_area: 34,
    product_id: null,
    estimated_amount: 34000000,
    contract_amount: 33500000,
    notes: '完了検査合格。引渡準備中。夫婦+子供1人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '村上 直子',
    name_kana: 'ムラカミ ナオコ',
    email: 'murakami.naoko@example.com',
    phone: '080-0123-4568',
    phone2: null,
    postal_code: '556-0011',
    address: '大阪府大阪市浪速区難波中1-2-3',
    tei_name: '村上様邸',
    partner_name: null,
    partner_name_kana: null,
    ownership_type: '単独',
    pipeline_status: '引渡' as PipelineStatus,
    lead_source: 'Instagram' as LeadSource,
    lead_date: '2024-02-15',
    event_date: '2024-02-20',
    member_date: '2024-02-25',
    meeting_date: '2024-03-05',
    application_date: '2024-03-20',
    decision_date: '2024-04-05',
    contract_date: '2024-04-20',
    groundbreaking_date: '2024-06-20',
    handover_date: '2025-01-05',
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 40,
    building_area: 25,
    product_id: null,
    estimated_amount: 28000000,
    contract_amount: 27500000,
    notes: '平屋完成。引渡書類準備中。単身。',
    kintone_record_id: null,
  },

  // 引渡済
  {
    tenant_id: null,
    name: '藤本 雅之',
    name_kana: 'フジモト マサユキ',
    email: 'fujimoto.masayuki@example.com',
    phone: '090-1234-5679',
    phone2: null,
    postal_code: '550-0014',
    address: '大阪府大阪市西区北堀江2-3-4',
    tei_name: '藤本様邸',
    partner_name: '藤本 香織',
    partner_name_kana: 'フジモト カオリ',
    ownership_type: '共有',
    pipeline_status: '引渡済' as PipelineStatus,
    lead_source: 'オーナー紹介' as LeadSource,
    lead_date: '2024-01-10',
    event_date: '2024-01-15',
    member_date: '2024-01-20',
    meeting_date: '2024-01-28',
    application_date: '2024-02-10',
    decision_date: '2024-02-25',
    contract_date: '2024-03-10',
    groundbreaking_date: '2024-05-10',
    handover_date: '2024-12-01',
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 52,
    building_area: 40,
    product_id: null,
    estimated_amount: 43000000,
    contract_amount: 42000000,
    notes: '引渡完了。アフターサポート継続中。夫婦+子供2人。',
    kintone_record_id: null,
  },
  {
    tenant_id: null,
    name: '橋本 康太',
    name_kana: 'ハシモト コウタ',
    email: 'hashimoto.kota@example.com',
    phone: '080-2345-6791',
    phone2: null,
    postal_code: '553-0003',
    address: '大阪府大阪市福島区福島3-4-5',
    tei_name: '橋本様邸',
    partner_name: '橋本 由紀',
    partner_name_kana: 'ハシモト ユキ',
    ownership_type: '共有',
    pipeline_status: '引渡済' as PipelineStatus,
    lead_source: 'モデルハウス見学会予約' as LeadSource,
    lead_date: '2023-11-01',
    event_date: '2023-11-05',
    member_date: '2023-11-10',
    meeting_date: '2023-11-18',
    application_date: '2023-12-01',
    decision_date: '2023-12-15',
    contract_date: '2024-01-05',
    groundbreaking_date: '2024-03-05',
    handover_date: '2024-11-01',
    lost_date: null,
    lost_reason: null,
    assigned_to: null,
    sub_assigned_to: null,
    land_area: 48,
    building_area: 36,
    product_id: null,
    estimated_amount: 38000000,
    contract_amount: 37000000,
    notes: '引渡完了。満足度調査実施済み。夫婦。',
    kintone_record_id: null,
  },

  // ボツ
  {
    tenant_id: null,
    name: '川口 達也',
    name_kana: 'カワグチ タツヤ',
    email: 'kawaguchi.tatsuya@example.com',
    phone: '090-3456-7892',
    phone2: null,
    postal_code: '577-0801',
    address: '大阪府東大阪市小阪1-2-3',
    tei_name: '川口様邸',
    partner_name: '川口 明美',
    partner_name_kana: 'カワグチ アケミ',
    ownership_type: '共有',
    pipeline_status: 'ボツ' as PipelineStatus,
    lead_source: 'その他' as LeadSource,
    lead_date: '2024-10-01',
    event_date: '2024-10-05',
    member_date: null,
    meeting_date: null,
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: '2024-10-20',
    lost_reason: '予算が合わず保留',
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 25000000,
    contract_amount: null,
    notes: '予算が合わず保留。将来再検討の可能性あり。夫婦+子供1人。',
    kintone_record_id: null,
  },

  // 他決
  {
    tenant_id: null,
    name: '西村 哲也',
    name_kana: 'ニシムラ テツヤ',
    email: 'nishimura.tetsuya@example.com',
    phone: '080-4567-8903',
    phone2: null,
    postal_code: '572-0042',
    address: '大阪府寝屋川市東大利町2-3-4',
    tei_name: '西村様邸',
    partner_name: '西村 恵理',
    partner_name_kana: 'ニシムラ エリ',
    ownership_type: '共有',
    pipeline_status: '他決' as PipelineStatus,
    lead_source: 'HP問合せ' as LeadSource,
    lead_date: '2024-09-01',
    event_date: '2024-09-05',
    member_date: '2024-09-10',
    meeting_date: '2024-09-18',
    application_date: null,
    decision_date: null,
    contract_date: null,
    groundbreaking_date: null,
    handover_date: null,
    lost_date: '2024-10-15',
    lost_reason: '他社で契約済み。価格差が理由。',
    assigned_to: null,
    sub_assigned_to: null,
    land_area: null,
    building_area: null,
    product_id: null,
    estimated_amount: 35000000,
    contract_amount: null,
    notes: '他社で契約済み。価格差が理由。夫婦+子供2人。',
    kintone_record_id: null,
  },
]

// 日付をランダム化するユーティリティ
export function randomizeDate(baseDate: string, daysRange: number): string {
  const date = new Date(baseDate)
  const randomDays = Math.floor(Math.random() * daysRange) - Math.floor(daysRange / 2)
  date.setDate(date.getDate() + randomDays)
  return date.toISOString().split('T')[0]
}

// サンプルデータを顧客ストアに読み込む関数
export function loadSampleCustomers(
  addCustomer: (customer: Omit<Customer, 'id' | 'created_at' | 'updated_at'>) => string
): string[] {
  const ids: string[] = []
  for (const customer of sampleCustomers) {
    const id = addCustomer(customer)
    ids.push(id)
  }
  return ids
}
